import pandas as pd
import numpy as np

def engineer_intelligence_features(df: pd.DataFrame, is_training: bool = False) -> pd.DataFrame:
    """
    Constructs the feature set for Anomaly Detection and Event Classification.
    Crucially drops 'event_type' to prevent target leakage.
    Uses 'expected_value' and 'deviation_pct' which must be provided (either from Simulator in train or Baseline V1 in real-time).
    """
    df = df.copy()
    
    # We expect these features to be present from Phase 3/4:
    # value, expected_value, deviation_pct, production_level, rate_of_change, rolling_std_3
    
    # Absolute deviation
    df['abs_deviation'] = df['value'] - df['expected_value']
    
    # Encode categorical contexts
    df = pd.get_dummies(df, columns=['machine_status', 'shift'], drop_first=False)
    
    # Ensure expected dummy columns
    expected_cols = [
        'shift_SHIFT_1', 'shift_SHIFT_2', 'shift_SHIFT_3',
        'machine_status_ACTIVE', 'machine_status_IDLE', 'machine_status_MAINTENANCE'
    ]
    for c in expected_cols:
        if c not in df.columns:
            df[c] = False
            
    # Compile features list
    features = [
        'value', 'expected_value', 'abs_deviation', 'deviation_pct', 
        'production_level', 'rate_of_change', 'rolling_std_3'
    ] + expected_cols
    
    # Fill any NaNs generated by rolling metrics for the first few rows
    df[features] = df[features].fillna(0)
    
    if is_training:
        # Keep the target column for training
        return df[features + ['event_type']]
        
    return df[features]
